# Generated by Django 2.2.6 on 2020-10-07 10:24

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_no', models.CharField(default=0, max_length=12)),
                ('alt_no', models.CharField(default=0, max_length=12)),
                ('address', models.CharField(default=0, max_length=500)),
                ('profile_pic', models.ImageField(upload_to='userpics')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_type', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(default=0, max_length=100)),
                ('Prod_description', models.CharField(blank=True, max_length=2000)),
                ('Prod_descriptiontwo', models.CharField(blank=True, max_length=2000)),
                ('Prod_descriptionthree', models.CharField(blank=True, max_length=2000)),
                ('Prod_descriptionfour', models.CharField(blank=True, max_length=2000)),
                ('Prod_descriptionfive', models.CharField(blank=True, max_length=2000)),
                ('Prod_descriptionsix', models.CharField(blank=True, max_length=2000)),
                ('prod_mrp', models.FloatField(default=0)),
                ('prod_price', models.FloatField(default=0)),
                ('prod_img', models.ImageField(default=0, upload_to='productimages')),
                ('prod_img2', models.ImageField(default=0, upload_to='productimages')),
                ('prod_img3', models.ImageField(default=0, upload_to='productimages')),
                ('add_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('prod_outofstock', models.BooleanField(default=False)),
                ('Prod_type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainpage.Product_type')),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainpage.Category')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_ki_id', models.IntegerField(default=0)),
                ('cust_ka_name', models.CharField(default=0, max_length=100)),
                ('cust_ka_username', models.CharField(default=0, max_length=100)),
                ('cust_ka_phone', models.CharField(default=0, max_length=12)),
                ('cust_ka_alt_no', models.CharField(default=0, max_length=12)),
                ('cust_ki_email', models.CharField(default=0, max_length=100)),
                ('cust_ka_address', models.CharField(default=0, max_length=500)),
                ('Product_ki_id', models.IntegerField(default=0)),
                ('Product_ki_quantity', models.IntegerField(default=1)),
                ('product_ki_price', models.FloatField(default=0)),
                ('product_ka_name', models.CharField(default=0, max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('add_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.ExtendedUser')),
                ('product_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Product')),
            ],
        ),
    ]
