# Generated by Django 2.2.6 on 2020-10-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(blank=True, null=True, upload_to='productimages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_img2',
            field=models.ImageField(blank=True, null=True, upload_to='productimages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_img3',
            field=models.ImageField(blank=True, null=True, upload_to='productimages'),
        ),
    ]
