# Generated by Django 2.2.6 on 2020-10-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20201025_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='productimages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_img2',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='productimages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_img3',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='productimages'),
        ),
    ]
