# Generated by Django 2.2.6 on 2020-10-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20201025_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(default=0, upload_to='productimages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_img2',
            field=models.ImageField(default=0, upload_to='productimages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_img3',
            field=models.ImageField(default=0, upload_to='productimages'),
        ),
    ]
