# Generated by Django 2.2.6 on 2020-10-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20201025_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_ki_img',
            field=models.ImageField(default=0, upload_to='productimages'),
        ),
    ]
