# Generated by Django 2.2.6 on 2021-01-03 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_auto_20210102_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=100)),
                ('amount', models.CharField(default=0, max_length=100)),
                ('payment_id', models.CharField(default=0, max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('orderperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.order')),
            ],
        ),
    ]
