# Generated by Django 2.2.6 on 2021-08-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_auto_20210103_1759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
