# Generated by Django 4.2.4 on 2023-10-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_product_prod_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default=0, upload_to='gallery'),
        ),
    ]
