# Generated by Django 4.2.4 on 2023-10-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_deal',
            field=models.CharField(choices=[('HOT DEALS', 'HOT DEALS'), ('New Arraivels', 'New Arraivels')], default=0, max_length=100),
        ),
    ]
