# Generated by Django 4.2.4 on 2023-10-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_alter_product_prod_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Prod_description',
        ),
    ]
